### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by krishanshelly** [pnp/sp-dev-modernization#521]
#### Problem Area
[X] **Page Transformation: Error during the use of page transformation from PnP PowerShell**
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
**Bug/Enhancement:
![ExceptionDetails](https://user-images.githubusercontent.com/38850003/91305753-20071800-e7c9-11ea-8863-1b89a6330c56.png)
[GitHubIssue.zip](https://github.com/pnp/sp-dev-modernization/files/5129895/GitHubIssue.zip)

**
We are trying to migrate web parts of type ContentByQueryWebPart from Classic Publishing Pages using ConvertTo-PnPClientSidePage PnP PowerShell scripts. As per the solution explained for the issue https://github.com/pnp/sp-dev-modernization/issues/353, we should be able to successfully migrate the ContentByQueryWebPart and ContentBySearchWebPart by adding CrossSiteTransformationSupported="true" in the webpartmapping.xml file for publishing portals too.

#### Observed Behavior
We are successfully able to migrate ContentBySearchWebPart web parts from Classic Publishing Portal pages to modern sites but getting error/exception while migrating the ContentByQueryWebPart web parts after setting CrossSiteTransformationSupported="true" in the webpartmapping.xml file.

#### Steps to Reproduce
Update the webpartmapping.xml file by adding CrossSiteTransformationSupported  attribute as shown below:

<WebPart Type="Microsoft.SharePoint.Publishing.WebControls.ContentByQueryWebPart, Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" CrossSiteTransformationSupported="true">

### More Details:
**PowerShell window output:**
  Processing ReadPage4.aspx
 Modernizing ReadPage4.aspx...
 Modernized ReadPage4.aspx!
Report saved as: c:\temp\Page-Transformation-Report-8-26-2020-4-00-32-PM.md
Script Complete! :)

**PnP PowerShell version output:**

ModuleType Version    Name                                ExportedCommands                                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                                
Binary     3.23.20... SharePointPnPPowerShellOnline       {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPClientSidePage...}   

**Exception Details:**

# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
8/26/2020 5:52:39 PM  |  00:00:10  |  [/Pages/ReadPage4.aspx](…/Pages/ReadPage4.aspx)  |  []()  |  A issue prevented successful transformation
## Errors during transformation

Date  |  Source Page  |  Operation  |  Message
-------------  |  -------------  |  -------------  |  -------------
8/26/2020 5:52:49 PM  |  /Pages/ReadPage4.aspx  |   Web Part Mapping  |  An error occurred processing functions - Exception has been thrown by the target of an invocation.    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SharePointPnP.Modernization.Framework.Functions.BaseFunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo methodInfo)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ExecutePropertyFunctions(String[] functionsToProcess, WebPart webPartData, WebPartEntity webPart, Property property)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)
8/26/2020 5:52:49 PM  |  /Pages/ReadPage4.aspx  |   Summary  |  A critical error occurred - transformation did not complete    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SharePointPnP.Modernization.Framework.Functions.BaseFunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo methodInfo)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ExecutePropertyFunctions(String[] functionsToProcess, WebPart webPartData, WebPartEntity webPart, Property property)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)
### 8/26/2020 5:52:49 PM - [/Pages/ReadPage4.aspx](…/Pages/ReadPage4.aspx)

_Exception has been thrown by the target of an invocation.   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SharePointPnP.Modernization.Framework.Functions.BaseFunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo methodInfo)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ExecutePropertyFunctions(String[] functionsToProcess, WebPart webPartData, WebPartEntity webPart, Property property)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_

**Comment by jansenbe** [comment]
Hey @krishanshelly ,

What you're doing is experimental, meaning we've never fully worked out the translation from on-premises CBQ web parts to online highlighted content web parts. If it works than that's fine, if not then...it's fine as well as this is feature that we're not supporting. In my view it's often better to just manually add the needed highlighted content web parts on the created modern pages and configure them accordingly. Automatic migration from CBS/CBQ already is only covering some cases as the target modern highlighted content web part works in a really different manner, adding on-premises into the mix further complicates things. We have no plans to further invest in supporting on-premises CBS/CBQ mapping to highlighted content. Hope you can understand that.

**Comment by krishanshelly** [comment]
Thanks for the update. As per your suggestion, we will try to manually configure Highlighted Content in the modern site for CBS/CBQ web parts.
